# Generated by Django 5.2 on 2025-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(max_length=199),
        ),
    ]
